/**
  * @file    eth_http/src/http_server.c
  * @brief   lwIP raw-API HTTP server for the bundled single-page site.
  *
  * Serves the single-page app (gzip, CSS/JS inlined, from Inc/web_assets.h,
  * generated by build_web.py from web/ + public/) plus the JSON API, adapted
  * for the CH32F207VCT6 (f207-evt-r1) board - one LED, two internal ADC
  * channels:
  *
  *   GET  /                 page, Content-Encoding: gzip
  *   GET  /api/leds         {"leds":[0]}           (real LED GPIO state)
  *   POST /api/leds         body {"leds":[0]}      -> applies to the LED
  *   GET  /api/adc          {"vrefint_mv":..,"temp_c":..,"ts":..}
  *   GET  /api/info         {"arch","lan_ip","public_ip":null,"geo":null,
  *                           "weather":null}
  *   GET  /public/<name>    raw image bytes (from the embedded_files[] table)
  *
  * The public IP / geo / weather fields are reported as null (the page shows
  * "N/A") because the board has no HTTP/TLS client.
  *
  * Responses are paced through tcp_sent: static bodies (page/images) are
  * written from flash without copying, JSON is built into the per-connection
  * buffer. NO_SYS / raw API - all callbacks run in the main loop while
  * ethernetif_input() is polled.
  */

#include "board.h"
#include "ch32f20x.h"
#include "lwip/opt.h"
#include "lwip/tcp.h"
#include "lwip/mem.h"
#include "lwip/ip_addr.h"
#include "lwip/netif.h"
#include "http_server.h"
#include "web_assets.h"

#include <stdio.h>
#include <string.h>

extern struct netif gnetif;

/* --------------------------------------------------------------------------
 * On-board LED: LED1 on PA0, LOW active (external wire on the f207-evt-r1).
 * ------------------------------------------------------------------------ */
#define LED_PORT  GPIOA
#define LED_PIN   GPIO_Pin_0

static void leds_init(void)
{
  GPIO_InitTypeDef gpio = {0};

  RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);

  gpio.GPIO_Pin   = LED_PIN;
  gpio.GPIO_Mode  = GPIO_Mode_Out_PP;
  gpio.GPIO_Speed = GPIO_Speed_50MHz;
  GPIO_Init(LED_PORT, &gpio);

  GPIO_WriteBit(LED_PORT, LED_PIN, Bit_SET);   /* OFF (active low) */
}

static int led_get(int i)
{
  (void)i;
  return GPIO_ReadOutputDataBit(LED_PORT, LED_PIN) == Bit_RESET ? 1 : 0;
}

static void led_set(int i, int on)
{
  (void)i;
  GPIO_WriteBit(LED_PORT, LED_PIN, on ? Bit_RESET : Bit_SET);
}

/* --------------------------------------------------------------------------
 * Internal ADC channels: die temperature (IN16) + VREFINT (IN17) -> VDDA.
 * Same measurement as blink_hello.
 * ------------------------------------------------------------------------ */
#define ADC_CH_TEMP    ADC_Channel_TempSensor
#define ADC_CH_VREFINT ADC_Channel_Vrefint

#define TEMP_V25_MV      1400.0f
#define TEMP_AVG_SLOPE   4.3f
#define VREFINT_TYP_V    1.20f

static int16_t s_CalibrationValue = 0;
static uint8_t adc_ready = 0;

static void adc_init(void)
{
  ADC_InitTypeDef ADC_InitStructure = {0};

  RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);
  RCC_ADCCLKConfig(RCC_PCLK2_Div8);

  ADC_DeInit(ADC1);
  ADC_InitStructure.ADC_Mode               = ADC_Mode_Independent;
  ADC_InitStructure.ADC_ScanConvMode       = DISABLE;
  ADC_InitStructure.ADC_ContinuousConvMode = DISABLE;
  ADC_InitStructure.ADC_ExternalTrigConv   = ADC_ExternalTrigConv_None;
  ADC_InitStructure.ADC_DataAlign          = ADC_DataAlign_Right;
  ADC_InitStructure.ADC_NbrOfChannel       = 1;
  ADC_Init(ADC1, &ADC_InitStructure);

  ADC_Cmd(ADC1, ENABLE);

  ADC_BufferCmd(ADC1, DISABLE);
  ADC_ResetCalibration(ADC1);
  while (ADC_GetResetCalibrationStatus(ADC1)) {}
  ADC_StartCalibration(ADC1);
  while (ADC_GetCalibrationStatus(ADC1)) {}
  s_CalibrationValue = Get_CalibrationValue(ADC1);
  ADC_BufferCmd(ADC1, ENABLE);

  ADC_TempSensorVrefintCmd(ENABLE);
}

static uint16_t adc_read_channel(uint8_t channel)
{
  uint16_t val;

  ADC_RegularChannelConfig(ADC1, channel, 1, ADC_SampleTime_239Cycles5);
  ADC_SoftwareStartConvCmd(ADC1, ENABLE);
  while (!ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC)) {}
  val = (uint16_t)ADC_GetConversionValue(ADC1);
  ADC_ClearFlag(ADC1, ADC_FLAG_EOC);
  return val;
}

static int32_t adc_calibrated(int32_t val)
{
  int32_t v = val + s_CalibrationValue;
  if (val == 0 || v < 0) return 0;
  if (val == 4095 || v > 4095) return 4095;
  return v;
}

static void adc_measure(float *vdda_mv, float *temp_c)
{
  int32_t r_temp, r_vrefint;

  if (!adc_ready)
  {
    adc_init();
    adc_ready = 1;
  }

  r_temp    = adc_calibrated(adc_read_channel(ADC_CH_TEMP));
  r_vrefint = adc_calibrated(adc_read_channel(ADC_CH_VREFINT));

  *vdda_mv = (r_vrefint != 0) ? (VREFINT_TYP_V * 4096.0f) / (float)r_vrefint * 1000.0f
                              : 0.0f;
  *temp_c  = (((float)r_temp * (*vdda_mv / 4096.0f) - TEMP_V25_MV)
              / TEMP_AVG_SLOPE + 25.0f);
}

/* --------------------------------------------------------------------------
 * TCP connection state + response pacing.
 * ------------------------------------------------------------------------ */
#define HTTP_RX_BUF   1024
#define HTTP_RESP_BUF 512

struct http_conn
{
  struct tcp_pcb *pcb;
  char rx[HTTP_RX_BUF];          /* accumulated request */
  size_t rx_len;
  char resp[HTTP_RESP_BUF];      /* header (+ JSON body) */
  size_t hdr_len;
  const uint8_t *body_ptr;       /* static body (page / image) or NULL */
  size_t body_len;
  u8_t body_static;              /* body_ptr points into const flash */
  size_t total_off;              /* bytes of response queued to lwIP */
  u8_t done;                     /* whole response queued */
};

static err_t http_recv(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err);
static err_t http_sent(void *arg, struct tcp_pcb *pcb, u16_t len);
static void  http_err(void *arg, err_t err);

/* Queue as much of the response as fits; the rest is sent from tcp_sent. */
static void conn_send(struct http_conn *c)
{
  for (;;)
  {
    const uint8_t *ptr;
    size_t left;
    u8_t flags;

    if (c->total_off < c->hdr_len)
    {
      ptr   = (const uint8_t *)c->resp + c->total_off;
      left  = c->hdr_len - c->total_off;
      flags = TCP_WRITE_FLAG_COPY;   /* header is in the per-conn buffer */
    }
    else
    {
      size_t bo = c->total_off - c->hdr_len;
      if (bo >= c->body_len)
      {
        c->done = 1;
        break;
      }
      ptr   = c->body_ptr + bo;
      left  = c->body_len - bo;
      flags = c->body_static ? 0 : TCP_WRITE_FLAG_COPY;
    }

    {
      u16_t chunk = (u16_t)LWIP_MIN(left, 2048);
      if (tcp_write(c->pcb, ptr, chunk, flags) != ERR_OK) break;
      c->total_off += chunk;
    }
  }
  tcp_output(c->pcb);
}

/* Close and free the connection once the response is fully queued. */
static void http_conn_close(struct http_conn *c)
{
  err_t err = tcp_close(c->pcb);
  if (err == ERR_OK)
  {
    tcp_arg(c->pcb, NULL);
    tcp_recv(c->pcb, NULL);
    tcp_sent(c->pcb, NULL);
    tcp_err(c->pcb, NULL);
    mem_free(c);
  }
  /* else: retried from tcp_sent when the send buffer drains */
}

static void http_reply_json(struct http_conn *c, const char *body)
{
  int n = snprintf(c->resp, sizeof(c->resp),
                   "HTTP/1.1 200 OK\r\n"
                   "Content-Type: application/json; charset=utf-8\r\n"
                   "Content-Length: %u\r\n"
                   "Cache-Control: no-store\r\n"
                   "Connection: close\r\n"
                   "\r\n"
                   "%s",
                   (unsigned)strlen(body), body);
  c->hdr_len = (size_t)n;
  c->body_ptr = NULL;
  c->body_len = 0;
  c->body_static = 0;
  c->total_off = 0;
  c->done = 0;
  conn_send(c);
  if (c->done) http_conn_close(c);
}

static void http_reply_err(struct http_conn *c, int code, const char *status)
{
  int n = snprintf(c->resp, sizeof(c->resp),
                   "HTTP/1.1 %d %s\r\n"
                   "Content-Type: text/plain\r\n"
                   "Content-Length: 0\r\n"
                   "Cache-Control: no-store\r\n"
                   "Connection: close\r\n"
                   "\r\n",
                   code, status);
  c->hdr_len = (size_t)n;
  c->body_ptr = NULL;
  c->body_len = 0;
  c->body_static = 0;
  c->total_off = 0;
  c->done = 0;
  conn_send(c);
  if (c->done) http_conn_close(c);
}

static void http_reply_static(struct http_conn *c, const char *ctype,
                              const char *encoding,
                              const uint8_t *data, size_t len)
{
  int n = snprintf(c->resp, sizeof(c->resp),
                   "HTTP/1.1 200 OK\r\n"
                   "Content-Type: %s\r\n"
                   "%s"
                   "Content-Length: %lu\r\n"
                   "Cache-Control: no-store\r\n"
                   "Connection: close\r\n"
                   "\r\n",
                   ctype,
                   encoding ? encoding : "",
                   (unsigned long)len);
  c->hdr_len = (size_t)n;
  c->body_ptr = data;
  c->body_len = len;
  c->body_static = 1;
  c->total_off = 0;
  c->done = 0;
  conn_send(c);
  if (c->done) http_conn_close(c);
}

/* --------------------------------------------------------------------------
 * API handlers.
 * ------------------------------------------------------------------------ */
static void api_leds(struct http_conn *c, const char *method, const char *body)
{
  if (strcmp(method, "POST") == 0 && body)
  {
    const char *b = strchr(body, '[');
    if (b)
    {
      int a = 0;
      int got = sscanf(b + 1, "%d", &a);
      if (got == 1) led_set(0, a ? 1 : 0);
    }
  }

  char resp[32];
  int n = snprintf(resp, sizeof(resp), "{\"leds\":[%d]}", led_get(0));
  http_reply_json(c, resp);
}

static void api_adc(struct http_conn *c)
{
  float vdda_mv, temp_c;
  char body[160];

  adc_measure(&vdda_mv, &temp_c);
  int n = snprintf(body, sizeof(body),
                   "{\"vrefint_mv\":%.1f,\"temp_c\":%.1f,\"ts\":%lu}",
                   vdda_mv, temp_c, (unsigned long)HAL_GetTick());
  http_reply_json(c, body);
}

static void api_info(struct http_conn *c)
{
  char body[512];
  char lan[16];

  ip4addr_ntoa_r(netif_ip4_addr(&gnetif), lan, sizeof(lan));
  int n = snprintf(body, sizeof(body),
                   "{\"arch\":\"cortex-m3\",\"lan_ip\":\"%s\",\"public_ip\":null,"
                   "\"geo\":null,\"weather\":null,\"ts\":%lu}",
                   lan, (unsigned long)HAL_GetTick());
  http_reply_json(c, body);
}

static void serve_public(struct http_conn *c, const char *path)
{
  for (unsigned i = 0; i < embedded_files_count; i++)
  {
    if (strcmp(path, embedded_files[i].path) == 0)
    {
      http_reply_static(c, embedded_files[i].ctype, NULL,
                        embedded_files[i].data, embedded_files[i].len);
      return;
    }
  }
  http_reply_err(c, 404, "Not Found");
}

static void process_request(struct http_conn *c)
{
  char method[8], path[1024];
  const char *body;

  if (sscanf(c->rx, "%7s %1023s", method, path) != 2)
  {
    http_reply_err(c, 400, "Bad Request");
    return;
  }
  {
    char *q = strchr(path, '?');
    if (q) *q = 0;
  }
  body = strstr(c->rx, "\r\n\r\n");
  body = body ? body + 4 : NULL;

  if (strcmp(path, "/") == 0 || strcmp(path, "/index.html") == 0)
  {
    http_reply_static(c, "text/html; charset=utf-8",
                      "Content-Encoding: gzip\r\n",
                      index_html_gz, index_html_gz_len);
  }
  else if (strcmp(path, "/api/leds") == 0)
  {
    api_leds(c, method, body);
  }
  else if (strcmp(path, "/api/adc") == 0)
  {
    api_adc(c);
  }
  else if (strcmp(path, "/api/info") == 0)
  {
    api_info(c);
  }
  else if (strcmp(path, "/favicon.ico") == 0)
  {
    http_reply_err(c, 204, "No Content");
  }
  else if (strncmp(path, "/public/", 8) == 0)
  {
    serve_public(c, path);
  }
  else
  {
    http_reply_err(c, 404, "Not Found");
  }
}

/* --------------------------------------------------------------------------
 * lwIP raw TCP callbacks.
 * ------------------------------------------------------------------------ */
static err_t http_recv(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err)
{
  struct http_conn *c = arg;

  if (err != ERR_OK) return ERR_OK;

  if (p == NULL)
  {
    if (c) { c->done = 1; http_conn_close(c); }
    return ERR_OK;
  }

  if (c)
  {
    if (c->rx_len + p->tot_len < sizeof(c->rx))
    {
      pbuf_copy_partial(p, c->rx + c->rx_len, p->tot_len, 0);
      c->rx_len += p->tot_len;
    }
    tcp_recved(pcb, p->tot_len);

    c->rx[c->rx_len] = 0;
    {
      char *hdr_end = strstr(c->rx, "\r\n\r\n");
      if (hdr_end)
      {
        long cl = 0;
        const char *clh = strstr(c->rx, "Content-Length:");
        if (clh)
        {
          clh += 15;
          while (*clh == ' ') clh++;
          cl = atol(clh);
        }
        {
          size_t want = (size_t)(hdr_end - c->rx) + 4 + (size_t)cl;
          if (c->rx_len >= want)
          {
            c->rx[want] = 0;
            process_request(c);
          }
        }
      }
    }
  }
  pbuf_free(p);
  return ERR_OK;
}

static err_t http_sent(void *arg, struct tcp_pcb *pcb, u16_t len)
{
  struct http_conn *c = arg;
  LWIP_UNUSED_ARG(pcb);
  LWIP_UNUSED_ARG(len);

  if (!c) return ERR_OK;
  if (c->done)
  {
    http_conn_close(c);
  }
  else
  {
    conn_send(c);
  }
  return ERR_OK;
}

static void http_err(void *arg, err_t err)
{
  struct http_conn *c = arg;
  LWIP_UNUSED_ARG(err);
  if (c) mem_free(c);
}

static err_t http_accept(void *arg, struct tcp_pcb *newpcb, err_t err)
{
  struct http_conn *c;
  LWIP_UNUSED_ARG(arg);

  if (err != ERR_OK || newpcb == NULL) return ERR_VAL;

  c = (struct http_conn *)mem_malloc(sizeof(*c));
  if (!c) return ERR_MEM;
  memset(c, 0, sizeof(*c));
  c->pcb = newpcb;

  tcp_arg(newpcb, c);
  tcp_recv(newpcb, http_recv);
  tcp_sent(newpcb, http_sent);
  tcp_err(newpcb, http_err);
  return ERR_OK;
}

/* --------------------------------------------------------------------------
 * Server entry point.
 * ------------------------------------------------------------------------ */
void http_server_init(void)
{
  struct tcp_pcb *pcb;

  leds_init();
  led_set(0, 0);

  pcb = tcp_new();
  if (!pcb) return;
  if (tcp_bind(pcb, IP_ADDR_ANY, 80) != ERR_OK) return;
  pcb = tcp_listen(pcb);
  if (!pcb) return;
  tcp_accept(pcb, http_accept);
}
